import { IconMenu1, IconMenu2, IconMenu3, IconMenu4, IconMenu5, IconUser } from '@/components/svg'
import Head from 'next/head'
import { useState } from 'react'

export default function MembersPage() {
    const [activeTab, setActiveTab] = useState(0);
    const [viewTab, setViewTab] = useState(1);
    const [tabList, setTabList] = useState([
        {icon: <IconMenu1 />},
        {icon: <IconMenu2 />},
        {icon: <IconMenu3 />},
        {icon: <IconMenu4 />},
        {icon: <IconMenu5 />},
    ]);

    const userTypes1 = [1,2,3,4,5,6];
    const userTypes2 = [1,2,3,4,5,6];
    const userTypes3 = [1,2,3,4,5];



    const handleTabeChange = index => {
        setActiveTab(index + 1);
        let _remove = tabList[index];
        let temp = [...tabList];
            temp.splice(index, 1);
            temp.unshift(_remove);
            setTabList(temp);

    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <main>
    <section className='perposal_form__wrapper position-relative pt-5 pb-5 cm_bord_wrapper_full' style={{backgroundImage: `url(assets/perposal-banner.png)`}}>
        <div className='g_6 perposal_form__graindaint position-absolute w-100 h-100 top-0 left-0' />
          <div className='container pt-5 position-relative z-3'>


            <div className='cm_view_tabs'>
                <span className={viewTab == 1 ? 'active' : ''} onClick={() => setViewTab(1)}>Government</span>
                <span className={viewTab == 2 ? 'active' : ''} onClick={() => setViewTab(2)}>Business</span>
            </div>



            <div className='cm_bord_wrapper'>
                
                <div className={`cm_bord_tabs ${activeTab ? 'has_active_tabs' : ''}`}>
                    <ul>
                        {tabList.map((item, i) =>  <li onClick={() => handleTabeChange(i)}>{item.icon}</li>)}
                    </ul>
                </div>


                <div className={`cm_bord_box ${activeTab ? 'has_show' : ''}`}>
                    <div className='cm_color_info'>
                        <h6 className='t1'>less than 1 day</h6>
                        <h6  className='t2'>less than 1 week</h6>
                        <h6  className='t3'>greater than 1 week</h6>
                    </div>


                    <div className='users_icons cercle_red'>
                      {userTypes1.map(item => <div className='users_icon' key={item}><IconUser /></div>)}
                    </div>

                    <div className='users_icons cercle_blue'>
                      {userTypes2.map(item => <div className='users_icon' key={item}><IconUser /></div>)}
                    </div>

                    <div className='users_icons cercle_green'>
                      {userTypes3.map(item => <div className='users_icon' key={item}><IconUser /></div>)}
                    </div>
                </div>


                

            </div>
         
          </div>
        </section>
    </main>
    </>
  )
}
